Develop
Lepochan/leotein pull request #2
Opened 2019-04-28 09:46 UTC by Lepochan

GemfileにSassのコードを書き込んだ。

2019-04-28 09:58 UTC, Lepochan commented
#1

2019-04-28 10:33 UTC, tnukjns approved these changes
.

2019-04-28 10:35 UTC, tnukjns requested changes

2019-04-28 10:35 UTC, tnukjns commented on Gemfile
>  end
ここの4行は必要ですか？

2019-04-28 10:35 UTC, tnukjns commented on Gemfile
> ++gem "sass", "3.5.0"
slimも追加しましょう！

2019-04-29 04:09 UTC, Lepochan commented on Gemfile
>  end
# Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'

ここだけ必要ないです。

2019-04-29 04:14 UTC, Lepochan commented on Gemfile
> ++gem "sass", "3.5.0"
追加しました！

2019-04-30 04:24 UTC, tnukjns commented on Gemfile
> ++gem "sass", "3.5.0"
@Lepochan 
どこに追加してありますか？

2019-04-30 08:12 UTC, Lepochan commented on Gemfile
> ++gem "sass", "3.5.0"
すみません、pushしました！
確認お願いします！

2019-04-30 10:17 UTC, tnukjns approved these changes

2019-04-30 10:19 UTC, tnukjns commented
LGTMです！！

![LGTM](https://lgtmoon.herokuapp.com/images/18899)

mergeして、delete branch してください。

2019-04-30 10:36 UTC, merged