ヘッダーとフッター
Lepochan/leotein pull request #8
Opened 2019-05-03 11:15 UTC by Lepochan

2019-05-03 11:22 UTC, tnukjns requested changes

2019-05-03 11:22 UTC, tnukjns commented on app/views/layouts/application.html.slim
> +      | SampleApp
leoteinの方が良いのでは？

2019-05-03 11:22 UTC, tnukjns commented on app/views/static_pages/help.html.erb
> +<h1>StaticPages#index</h1>
helpっているんだっけ？
必要なければファイルとかアクションとかルーティングから全部消去しましょう！

2019-05-03 11:22 UTC, tnukjns commented on app/views/static_pages/help.html.slim
> -  | StaticPages#index
このファイルもいらなくないですか？

2019-05-03 11:22 UTC, tnukjns commented on app/views/static_pages/home.html.erb
> -<p><a href="https://proteinbible.jp" target="_blank">ようこそ、世界！</a></p>
slimにしましょう

2019-05-03 11:22 UTC, tnukjns commented on tmp/cache/assets/sprockets/v3.0/-G/-G2mL8SCTp1A5kGqEn-wEs5J-6AyYQUaW_mgOnQLjKs.cache
> +I"�app/assets/stylesheets/application.css?type=text/css&pipeline=debug&id=08fc119231bbac6e66d0fe0e580f98ddffc50ffefc5780e28e9b096c5ef11eb5:ET
git ignoreで不必要なファイルはgithubに上がらないようにしましょう。

2019-05-03 11:22 UTC, tnukjns commented on app/assets/stylesheets/application.css
> +  padding:40px;
sassにしましょう。
このプルリクエストで不要なスタイルは削除してください。

2019-05-03 11:23 UTC, Lepochan commented
・sassも使うようにする
・slim, git, githubはこのまま使っていく

2019-05-04 06:18 UTC, Lepochan commented on app/views/layouts/application.html.slim
> +      | SampleApp
doneです！

2019-05-04 06:19 UTC, Lepochan commented on app/views/static_pages/help.html.erb
> +<h1>StaticPages#index</h1>
doneです！

2019-05-04 06:19 UTC, Lepochan commented on app/views/static_pages/help.html.slim
> -  | StaticPages#index
doneです！

2019-05-04 06:21 UTC, Lepochan commented on app/views/static_pages/home.html.erb
> -<p><a href="https://proteinbible.jp" target="_blank">ようこそ、世界！</a></p>
doneです！

2019-05-04 06:31 UTC, Lepochan commented on app/assets/stylesheets/application.css
> +  padding:40px;
doneです！

2019-05-04 06:37 UTC, Lepochan commented on tmp/cache/assets/sprockets/v3.0/-G/-G2mL8SCTp1A5kGqEn-wEs5J-6AyYQUaW_mgOnQLjKs.cache
> +I"�app/assets/stylesheets/application.css?type=text/css&pipeline=debug&id=08fc119231bbac6e66d0fe0e580f98ddffc50ffefc5780e28e9b096c5ef11eb5:ET
doneです！

2019-05-07 13:39 UTC, tnukjns commented on tmp/cache/assets/sprockets/v3.0/-G/-G2mL8SCTp1A5kGqEn-wEs5J-6AyYQUaW_mgOnQLjKs.cache
> +I"�app/assets/stylesheets/application.css?type=text/css&pipeline=debug&id=08fc119231bbac6e66d0fe0e580f98ddffc50ffefc5780e28e9b096c5ef11eb5:ET
<img width="1285" alt="スクリーンショット 2019-05-07 22 38 13" src="https://user-images.githubusercontent.com/11924387/57303742-ec5a3780-7118-11e9-993a-6d9a3272f11e.png">

2019-05-07 13:40 UTC, tnukjns commented on tmp/cache/assets/sprockets/v3.0/-G/-G2mL8SCTp1A5kGqEn-wEs5J-6AyYQUaW_mgOnQLjKs.cache
> +I"�app/assets/stylesheets/application.css?type=text/css&pipeline=debug&id=08fc119231bbac6e66d0fe0e580f98ddffc50ffefc5780e28e9b096c5ef11eb5:ET
このあたりとかgithubで管理する必要なさそうですよね？
参考例を調べて、igonoreしてみてください！

2019-05-07 13:41 UTC, tnukjns commented
masterにmergeするんですか？

<img width="395" alt="スクリーンショット 2019-05-07 22 41 19" src="https://user-images.githubusercontent.com/11924387/57303893-3e9b5880-7119-11e9-895d-6e19719e55a5.png">

2019-05-09 06:45 UTC, merged